env: "prod" #local, prod
#storage_path: "postgresql://postgres:qwerty@db:5432/proto-stream-db?sslmode=disable"

#db:
#  username: "postgres"
#  host: "localhost"
#  port: "5432"
#  dbname: "proto-stream-db"
#  sslmode: "disable"
#  password: "qwerty"

http_server:
  address: "0.0.0.0:8082"
  timeout: 4s
  idle_timeout: 60s
  cert_file: "/etc/ssl/certificate.crt"
  key_file: "/etc/ssl/private.key"

cors_origin:
  - "http://45.145.65.245"
  - "http://xn--b1aaee5as4b.xn--p1ai"
  - "https://xn--b1aaee5as4b.xn--p1ai"

cache:
  ttl: 3600s

auth:
  accessTokenTTL: 120m
  refreshTokenTTL: 3600m
#  jwt_secret: "xxxxxxxxx"